### ISSUE TITLE
When change city, the point on the map stays the same

### ISSUE THREAD

**Issue by rusiaikinat** [jmix-framework/jmix-v1-bookstore#63]
### TC
Set `sity` on Customer screen -> OK
Open the user card again
Change `sity` on Customer screen
Click ![image](https://user-images.githubusercontent.com/114649487/215695369-197a97b6-6b4b-4dd5-9530-b75a4775f47f.png)

### AR
Point on the map stays the same
![image](https://user-images.githubusercontent.com/114649487/215695300-d5927581-41dd-4183-aeda-766aa6f81276.png)

and linking to the city on the screen `Employee` does not work

**Comment by mariodavid** [comment]
both fixed in https://github.com/jmix-framework/jmix-bookstore/commit/63f31b1bbbc7668f23fdd084ebfc1c728119e2ef
