### ISSUE TITLE
In some screens, the authorization lable goes beyond the window

### ISSUE THREAD

**Issue by rusiaikinat** [jmix-framework/jmix-v1-bookstore#65]
**env**
display 1920x1080 
chrome browser

**TC**
Open project
Pay attention to the section of the screen with user authorization data
Select menu item:

AR
![image](https://user-images.githubusercontent.com/114649487/215754995-1deb1a38-70df-4e96-a2be-6cd77bbabc04.png)

Orders - the section has moved to the right
HR - Users
BPM - Start process
BPM - Decision table modeler - the section has moved to the right
Reports - Reports
Reports - Reports - Reports
Reports - Run reports
Administrators - Resource roles
Administrators - Row-level roles
Administrators - Tenants
Administrators - Notifications
Administrators - Quartz jobs

**Comment by mariodavid** [comment]
fixed in https://github.com/jmix-framework/jmix-bookstore/commit/e213b3d23ce1ecca2743768f071af10f61106873
